deployment:
  tasks:
    - export REPOPATH=/home/repositories/performance/*
    - export SITEPATH=/home/repositories/performance/public/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
